<a href="https://colab.research.google.com/github/b-bhupendra/Celestial-Database/blob/main/L9_Eigenvalues_and_eigenvectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
A = np.array([[2,-2,3],[1,1,1],[1,3,-1]])

In [11]:
# calculate eigenpairs
def print_eig_val_vect(A):
    values, vectors = np.linalg.eig(A)
    print(values)
    print(vectors) # these are vectors of unit length

In [13]:
A = np.array([[2,0,0],[0,1,0],[0,0,-1]])
print_eig_val_vect(A)

[ 2.  1. -1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
